(function(){'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function r(a,b){if(b)a:{var c=ea;a=a.split(".");for(var f=0;f<a.length-1;f++){var d=a[f];if(!(d in c))break a;c=c[d]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(f+(g||"")+"_"+d++,g)}function c(g,k){this.g=g;p(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.g};var f="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=ea[b[c]];typeof f==="function"&&typeof f.prototype[a]!="function"&&p(f.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ha=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=ia;
function ma(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(u)u(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,c);f&&Object.defineProperty(a,c,f)}else a[c]=b[c];a.F=b.prototype}function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
function na(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}r("Reflect.setPrototypeOf",function(a){return a?a:u?function(b,c){try{return u(b,c),!0}catch(f){return!1}}:null});r("Object.setPrototypeOf",function(a){return a||u});function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(h){this.g=(e+=Math.random()+1).toString();if(h){h=v(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function f(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function d(h){if(!w(h,k)){var l=new c;p(h,k,{value:l})}}function g(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(n){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var e=0;b.prototype.set=function(h,l){if(!f(h))throw Error("Invalid WeakMap key");d(h);if(!w(h,k))throw Error("WeakMap key fail: "+h);h[k][this.g]=l;return this};b.prototype.get=function(h){return f(h)&&w(h,k)?h[k][this.g]:void 0};b.prototype.has=function(h){return f(h)&&w(h,
k)&&w(h[k],this.g)};b.prototype.delete=function(h){return f(h)&&w(h,k)&&w(h[k],this.g)?delete h[k][this.g]:!1};return b});
r("Map",function(a){function b(){var e={};return e.l=e.next=e.head=e}function c(e,h){var l=e[1];return fa(function(){if(l){for(;l.head!=e[1];)l=l.l;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function f(e,h){var l=h&&typeof h;l=="object"||l=="function"?g.has(h)?l=g.get(h):(l=""+ ++k,g.set(h,l)):l="p_"+h;var m=e[0][l];if(m&&w(e[0],l))for(e=0;e<m.length;e++){var n=m[e];if(h!==h&&n.key!==n.key||h===n.key)return{id:l,list:m,index:e,j:n}}return{id:l,
list:m,index:-1,j:void 0}}function d(e){this[0]={};this[1]=b();this.size=0;if(e){e=v(e);for(var h;!(h=e.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var e=Object.seal({x:4}),h=new a(v([[e,"s"]]));if(h.get(e)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=e||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var g=new WeakMap;d.prototype.set=function(e,h){e=e===0?0:e;var l=f(this,e);l.list||(l.list=this[0][l.id]=[]);l.j?l.j.value=h:(l.j={next:this[1],l:this[1].l,head:this[1],key:e,value:h},l.list.push(l.j),this[1].l.next=l.j,this[1].l=l.j,this.size++);return this};d.prototype.delete=function(e){e=f(this,e);return e.j&&e.list?(e.list.splice(e.index,1),e.list.length||delete this[0][e.id],e.j.l.next=e.j.next,e.j.next.l=e.j.l,e.j.head=
null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].l=b();this.size=0};d.prototype.has=function(e){return!!f(this,e).j};d.prototype.get=function(e){return(e=f(this,e).j)&&e.value};d.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};d.prototype.keys=function(){return c(this,function(e){return e.key})};d.prototype.values=function(){return c(this,function(e){return e.value})};d.prototype.forEach=function(e,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,e.call(h,m[1],m[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var k=0;return d});r("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});r("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});r("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
r("Array.prototype.includes",function(a){return a?a:function(b,c){var f=this;f instanceof String&&(f=String(f));var d=f.length;c=c||0;for(c<0&&(c=Math.max(c+d,0));c<d;c++){var g=f[c];if(g===b||Object.is(g,b))return!0}return!1}});
r("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});r("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var x=this||self;function oa(a){return a};var pa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function qa(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function ra(a){a=a===void 0?document:a;return a.createElement("img")};function ua(a,b,c){var f=!1;f=f===void 0?!1:f;a.google_image_requests||(a.google_image_requests=[]);var d=ra(a.document);if(c){var g=function(){if(c){var k=a.google_image_requests,e=pa(k,d);e>=0&&Array.prototype.splice.call(k,e,1)}typeof d.removeEventListener==="function"&&d.removeEventListener("load",g,!1);typeof d.removeEventListener==="function"&&d.removeEventListener("error",g,!1)};typeof d.addEventListener==="function"&&d.addEventListener("load",g,!1);typeof d.addEventListener==="function"&&
d.addEventListener("error",g,!1)}f&&(d.attributionSrc="");d.src=b;a.google_image_requests.push(d)};function va(a){x.setTimeout(function(){throw a;},0)};var wa={},y=null;var xa,ya=typeof String.prototype.isWellFormed==="function",za=typeof TextEncoder!=="undefined";var Aa=void 0;function Ba(a){a=Error(a);qa(a,"warning");return a};var A=typeof Symbol==="function"&&typeof Symbol()==="symbol";function B(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Ca=B("jas",void 0,!0),C=B(void 0,"1oa"),Da=B(void 0,"0actk"),D=B("m_m","D",!0);var Ea={u:{value:0,configurable:!0,writable:!0,enumerable:!1}},Fa=Object.defineProperties,F=A?Ca:"u",G,Ga=[];H(Ga,7);G=Object.freeze(Ga);function H(a,b){A||F in a||Fa(a,Ea);a[F]=b};var I={};function K(a,b){return b===void 0?a.g!==Ha&&!!(2&(a.h[F]|0)):!!(2&b)&&a.g!==Ha}var Ha={},Ia=Object.freeze({});function Ja(a,b,c){b=b&128?0:-1;var f=a.length,d;if(d=!!f)d=a[f-1],d=d!=null&&typeof d==="object"&&d.constructor===Object;for(var g=f+(d?-1:0),k=0;k<g;k++)c(k-b,a[k]);if(d){a=a[f-1];for(var e in a)!isNaN(e)&&c(+e,a[e])}};var Ka=typeof x.BigInt==="function"&&typeof x.BigInt(0)==="bigint";var La=Number.MIN_SAFE_INTEGER.toString(),Ma=Ka?BigInt(Number.MIN_SAFE_INTEGER):void 0,Na=Number.MAX_SAFE_INTEGER.toString(),Oa=Ka?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Pa(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var f=a[c],d=b[c];if(f>d)return!1;if(f<d)return!0}};var Qa=0,Ra=0,Sa;var Ta=Number.isFinite;function Ua(a){if(!Ta(a))throw Ba("enum");return a|0}function Va(a){if(typeof a!=="number")throw Ba("int32");if(!Ta(a))throw Ba("int32");return a|0}function Wa(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return Ta(a)?a|0:void 0}function L(a){if(a!=null&&typeof a!=="string")throw Error();return a};function Xa(a){return a};function Ya(a,b,c,f){var d=f!==void 0;f=!!f;var g=[],k=a.length,e=4294967295,h=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=k&&a[k-1];n!=null&&typeof n==="object"&&n.constructor===Object?(k--,e=k):n=void 0;if(l&&!(b&128)&&!d){h=!0;var q;e=((q=Za)!=null?q:Xa)(e-m,m,a,n)+m}}b=void 0;for(d=0;d<k;d++)if(q=a[d],q!=null&&(q=c(q,f))!=null)if(l&&d>=e){var J=d-m,E=void 0;((E=b)!=null?E:b={})[J]=q}else g[d]=q;if(n)for(var z in n)a=n[z],a!=null&&(a=c(a,f))!=null&&(k=+z,d=void 0,l&&!Number.isNaN(k)&&
(d=k+m)<e?g[d]=a:(k=void 0,((k=b)!=null?k:b={})[z]=a));b&&(h?g.push(b):g[e]=b);return g}function $a(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Ka?a>=Ma&&a<=Oa:a[0]==="-"?Pa(a,La):Pa(a,Na))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[F]|0;return a.length===0&&b&1?void 0:Ya(a,b,$a)}if(a[D]===I)return ab(a);return}return a}var Za;function ab(a){a=a.h;return Ya(a,a[F]|0,$a)};var bb,cb;function db(a){switch(typeof a){case "boolean":return bb||(bb=[0,void 0,!0]);case "number":return a>0?void 0:a===0?cb||(cb=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}
function M(a,b,c,f){f=f===void 0?0:f;if(a==null){var d=32;c?(a=[c],d|=128):a=[];b&&(d=d&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");d=a[F]|0;2048&d&&!(2&d)&&fb();if(d&256)throw Error("farr");if(d&64)return f!==0||d&2048||H(a,d|2048),a;if(c&&(d|=128,c!==a[0]))throw Error("mid");a:{c=a;d|=64;var g=c.length;if(g){var k=g-1,e=c[k];if(e!=null&&typeof e==="object"&&e.constructor===Object){b=d&128?0:-1;k-=b;if(k>=1024)throw Error("pvtlmt");for(var h in e)g=+h,g<k&&(c[g+b]=e[h],delete e[h]);
d=d&-8380417|(k&1023)<<13;break a}}if(b){h=Math.max(b,g-(d&128?0:-1));if(h>1024)throw Error("spvt");d=d&-8380417|(h&1023)<<13}}}d|=64;f===0&&(d|=2048);H(a,d);return a}function fb(){if(Da!=null){var a;var b=(a=Aa)!=null?a:Aa={};a=b[Da]||0;a>=5||(b[Da]=a+1,b=Error(),qa(b,"incident"),va(b))}};function gb(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[F]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=N(a,c,!1,b&&!(c&16)):(b=a,A||F in b||Fa(b,Ea),b[F]|=34,c&4&&Object.freeze(a)));return a}if(a[D]===I){b=a.h;var f=b[F]|0;K(a,f)?c=a:c=N(b,f);return c}}function N(a,b,c,f){f!=null||(f=!!(34&b));a=Ya(a,b,gb,f);f=32;c&&(f|=2);b=b&8380609|f;H(a,b);return a}function hb(a){if(a.g!==Ha)return!1;var b=a.h;b=N(b,b[F]|0);a.h=b;a.g=void 0;a.m=void 0;return!0}
function O(a){if(!hb(a)&&K(a,a.h[F]|0))throw Error();};function ib(a,b){if(b===-1)return null;var c=b+-1,f=a.length-1;if(!(f<0)){if(c>=f)if(a=a[f],a!=null&&typeof a==="object"&&a.constructor===Object)b=a[b];else if(c===f)b=a;else return;else b=a[c];return b}}function jb(a,b,c){O(a);a=a.h;P(a,a[F]|0,b,c)}
function P(a,b,c,f){var d=c+-1,g=a.length-1;if(g>=0&&d>=g){var k=a[g];if(k!=null&&typeof k==="object"&&k.constructor===Object)return k[c]=f,b}if(d<=g)return a[d]=f,b;if(f!==void 0){var e;g=((e=b)!=null?e:b=a[F]|0)>>13&1023||536870912;c>=g?f!=null&&(d={},a[g+-1]=(d[c]=f,d)):a[d]=f}return b}function Q(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function R(a,b,c,f){O(a);a=a.h;var d=a[F]|0;if(f==null){var g=kb(a);if(lb(g,a,d,c)===b)g.set(c,0);else return}else{g=kb(a);var k=lb(g,a,d,c);k!==b&&(k&&(d=P(a,d,k)),g.set(c,b))}P(a,d,b,f)}function kb(a){if(A){var b;return(b=a[C])!=null?b:a[C]=new Map}if(C in a)return a[C];b=new Map;Object.defineProperty(a,C,{value:b});return b}function lb(a,b,c,f){var d=a.get(f);if(d!=null)return d;for(var g=d=0;g<f.length;g++){var k=f[g];ib(b,k)!=null&&(d!==0&&(c=P(b,c,d)),d=k)}a.set(f,d);return d}
function mb(a,b,c,f,d,g,k,e){var h=K(a,c);g=h?1:g;k=!!k||g===3;h=e&&!h;(g===2||h)&&hb(a)&&(b=a.h,c=b[F]|0);a=ib(b,d);e=Array.isArray(a)?a:G;var l=e===G?7:e[F]|0;a=l;2&c&&(a|=2);var m=a|1;if(a=!(4&m)){var n=e,q=c,J=!!(2&m);J&&(q|=2);for(var E=!J,z=!0,ba=0,sa=0;ba<n.length;ba++){var t=n[ba];var ca=f;if(t==null||typeof t!=="object"||t[D]!==I)if(Array.isArray(t)){var eb=t[F]|0;var ta=eb|q&32;ta|=q&2;ta!==eb&&H(t,ta);t=new ca(t)}else t=void 0;t instanceof f&&(J||(ca=K(t),E&&(E=!ca),z&&(z=ca)),n[sa++]=
t)}sa<ba&&(n.length=sa);m|=4;m=z?m&-4097:m|4096;m=E?m|8:m&-9}m!==l&&(H(e,m),2&m&&Object.freeze(e));if(h&&!(8&m||!e.length&&(g===1||(g!==4?0:2&m||!(16&m)&&32&c)))){Q(m)&&(e=Array.prototype.slice.call(e),m=nb(m,c),c=P(b,c,d,e));f=e;h=m;for(l=0;l<f.length;l++)n=f[l],m=n.h,q=m[F]|0,m=K(n,q)?new n.constructor(N(m,q,!1)):n,n!==m&&(f[l]=m);h|=8;m=h=f.length?h|4096:h&-4097;H(e,m)}h=f=m;g===1||(g!==4?0:2&f||!(16&f)&&32&c)?Q(f)||(f|=!e.length||a&&!(4096&f)||32&c&&!(4096&f||16&f)?2:256,f!==h&&H(e,f),Object.freeze(e)):
(g===2&&Q(f)&&(e=Array.prototype.slice.call(e),h=0,f=nb(f,c),P(b,c,d,e)),Q(f)||(k||(f|=16),f!==h&&H(e,f)));return e}function ob(a,b){var c=a.h;return mb(a,c,c[F]|0,pb,b,void 0===Ia?2:4,!1,!0)}
function qb(a,b,c){O(a);var f=a.h,d=f[F]|0;if(c==null)return P(f,d,b),a;for(var g=c===G?7:c[F]|0,k=g,e=Q(g),h=e||Object.isFrozen(c),l=!0,m=!0,n=0;n<c.length;n++){var q=c[n];e||(q=K(q),l&&(l=!q),m&&(m=q))}e||(g=l?13:5,g=m?g&-4097:g|4096);h&&g===k||(c=Array.prototype.slice.call(c),k=0,g=nb(g,d));g!==k&&H(c,g);P(f,d,b,c);return a}function nb(a,b){return a=(2&b?a|2:a&-3)&-273};function S(a,b,c){this.h=M(a,b,c)}S.prototype.toJSON=function(){var a=ab(this);return a};S.prototype[D]=I;S.prototype.toString=function(){return this.h.toString()};function rb(){this.g=[]}rb.prototype.length=function(){return this.g.length};rb.prototype.end=function(){var a=this.g;this.g=[];return a};function T(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function sb(a,b){if(b>=0)T(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function tb(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function ub(){this.m=[];this.i=0;this.g=new rb}function vb(a,b){b.length!==0&&(a.m.push(b),a.i+=b.length)}function wb(a,b){T(a.g,b*8+2);b=a.g.end();vb(a,b);b.push(a.i);return b}function xb(a,b){var c=b.pop();for(c=a.i+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.i++;b.push(c);a.i++};function U(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var yb=U(),zb=U();function V(a,b){this.g=a;a=oa(yb);this.i=!!a&&b===a||!1}function Ab(){var a=Bb;var b=b===void 0?yb:b;return new V(a,b)}function Bb(a,b,c,f,d){b=Cb(b,f);b!=null&&(c=wb(a,c),d(b,a),xb(a,c))}var Db=Ab(),Eb=Ab(),Fb=Symbol(),Gb=Symbol(),Hb,Ib;
function Jb(a){var b=Kb,c=Lb,f=a[Fb];if(f)return f;f={};f.C=a;f.o=db(a[0]);var d=a[1],g=1;d&&d.constructor===Object&&(f.s=d,d=a[++g],typeof d==="function"&&(f.v=!0,Hb!=null||(Hb=d),Ib!=null||(Ib=a[g+1]),d=a[g+=2]));for(var k={};d&&Array.isArray(d)&&d.length&&typeof d[0]==="number"&&d[0]>0;){for(var e=0;e<d.length;e++)k[d[e]]=d;d=a[++g]}for(e=1;d!==void 0;){typeof d==="number"&&(e+=d,d=a[++g]);var h=void 0;if(d instanceof V)var l=d;else l=Db,g--;d=void 0;if((d=l)==null?0:d.i){d=a[++g];h=a;var m=g;
typeof d==="function"&&(d=d(),h[m]=d);h=d}d=a[++g];m=e+1;typeof d==="number"&&d<0&&(m-=d,d=a[++g]);for(;e<m;e++){var n=k[e];h?c(f,e,l,h,n):b(f,e,l,n)}}return a[Fb]=f}function Cb(a,b){if(a instanceof S)return a.h;if(Array.isArray(a))return M(a,b[0],b[1],2)};function Kb(a,b,c){a[b]=c.g}function Lb(a,b,c,f){var d,g,k=c.g;a[b]=function(e,h,l){return k(e,h,l,g||(g=Jb(f).o),d||(d=Mb(f)))}}function Mb(a){var b=a[Gb];if(!b){var c=Jb(a);b=function(f,d){return Nb(f,d,c)};a[Gb]=b}return b}function Nb(a,b,c){Ja(a,a[F]|0,function(f,d){if(d!=null){var g=Ob(c,f);g&&g(b,d,f)}})}
function Ob(a,b){var c=a[b];if(c)return c;if(c=a.s)if(c=c[b]){c=Array.isArray(c)?c[0]instanceof V?c:[Eb,c]:[c,void 0];var f=c[0].g;if(c=c[1]){var d=Mb(c),g=Jb(c).o;c=a.v?Ib(g,d):function(k,e,h){return f(k,e,h,g,d)}}else c=f;return a[b]=c}};function W(a,b){return new V(a,b)}
function Pb(a,b,c){b=b==null||typeof b==="string"?b:void 0;if(b!=null){var f=!1;f=f===void 0?!1:f;if(za){if(f&&(ya?!b.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(b)))throw Error("Found an unpaired surrogate");b=(xa||(xa=new TextEncoder)).encode(b)}else{for(var d=0,g=new Uint8Array(3*b.length),k=0;k<b.length;k++){var e=b.charCodeAt(k);if(e<128)g[d++]=e;else{if(e<2048)g[d++]=e>>6|192;else{if(e>=55296&&e<=57343){if(e<=56319&&k<b.length){var h=b.charCodeAt(++k);
if(h>=56320&&h<=57343){e=(e-55296)*1024+h-56320+65536;g[d++]=e>>18|240;g[d++]=e>>12&63|128;g[d++]=e>>6&63|128;g[d++]=e&63|128;continue}else k--}if(f)throw Error("Found an unpaired surrogate");e=65533}g[d++]=e>>12|224;g[d++]=e>>6&63|128}g[d++]=e&63|128}}b=d===g.length?g:g.subarray(0,d)}T(a.g,c*8+2);T(a.g,b.length);vb(a,a.g.end());vb(a,b)}}
var Qb=W(function(a,b,c){b=b==null||typeof b==="number"?b:b==="NaN"||b==="Infinity"||b==="-Infinity"?Number(b):void 0;b!=null&&(T(a.g,c*8+1),a=a.g,c=Sa||(Sa=new DataView(new ArrayBuffer(8))),c.setFloat64(0,+b,!0),Qa=c.getUint32(0,!0),Ra=c.getUint32(4,!0),tb(a,Qa),tb(a,Ra))},U()),Rb=W(function(a,b,c){b=Wa(b);b!=null&&b!=null&&(T(a.g,c*8),sb(a.g,b))},U()),Sb=W(Pb,zb),Tb=W(Pb,zb),Ub,Vb=void 0;Vb=Vb===void 0?yb:Vb;
Ub=new V(function(a,b,c,f,d){if(Array.isArray(b))for(var g=0;g<b.length;g++){var k=a,e=c,h=d,l=Cb(b[g],f);l!=null&&(e=wb(k,e),h(l,k),xb(k,e))}},Vb);var Wb=W(function(a,b,c){b=Wa(b);b!=null&&(b=parseInt(b,10),T(a.g,c*8),sb(a.g,b))},U());function pb(a){this.h=M(a)}ma(pb,S);var Xb=[1,2,3],Yb=[4,5];var Zb=[0,Xb,Yb,Wb,-1,Tb,Qb,Tb,Rb];function $b(a){this.h=M(a)}ma($b,S);$b.prototype.i=function(a){return function(){var b=new ub;Nb(this.h,b,Jb(a));vb(b,b.g.end());for(var c=new Uint8Array(b.i),f=b.m,d=f.length,g=0,k=0;k<d;k++){var e=f[k];c.set(e,g);g+=e.length}b.m=[c];return c}}([0,Ub,Zb,Sb,1,Sb,Rb]);function ac(a){this.h=M(a)}ma(ac,S);ac.prototype.setData=function(a,b){var c=pb;O(this);var f=this.h;c=mb(this,f,f[F]|0,c,2,2,!0);if(typeof a!=="number"||a<0||a>c.length)throw Error();a!=void 0?c.splice(a,1,b):c.push(b);f=a=c===G?7:c[F]|0;K(b)?(a&=-9,c.length===1&&(a&=-4097)):a|=4096;a!==f&&H(c,a);return this};function bc(){this.data=[];this.i=[];this.g=[]}bc.prototype.setData=function(a,b,c){this.g.includes(c)&&this.data.push({key:a,value:b,channel:c})};function cc(a){return a.data.some(function(b){return b.channel===1})}bc.prototype.setAttribute=function(a,b){this.i.push({key:a,value:b})};
function dc(a,b,c,f){var d=new pb;typeof a==="string"?R(d,3,Xb,L(a)):f?R(d,1,Xb,a==null?a:Ua(a)):R(d,2,Xb,a==null?a:Ua(a));if(typeof b==="number"){if(b==null)a=b;else{if(typeof b!=="number")throw Error("Value of float/double field must be a number, found "+typeof b+": "+b);a=b}R(d,4,Yb,a)}else R(d,5,Yb,L(b));c&&jb(d,6,c==null?c:Va(c));return d};function X(){this.g=new bc;this.m=Date.now()}
X.prototype.init=function(a,b,c,f,d,g){var k=this;this.g.g.push.apply(this.g.g,b instanceof Array?b:na(v(b)));this.B=a;this.i=d;this.A=c;if(f)for(a=v(f),b=a.next();!b.done;b=a.next())c=v(b.value),b=c.next().value,c=c.next().value,this.g.setAttribute(b,c);if(g){g=v(g);for(a=g.next();!a.done;a=g.next())c=v(a.value),a=c.next().value,b=c.next().value,c=c.next().value,this.setData(a,b,c);document.readyState==="complete"?this.send():window.addEventListener("load",function(){k.send()})}};
X.prototype.getBaseTime=function(){return this.m};X.prototype.setData=function(a,b,c){this.g.setData(a,b,c)};X.prototype.setAttribute=function(a,b){this.g.setAttribute(a,b)};X.prototype.send=function(a){var b=this,c=cc(this.g)?0:100;a=a!=null?a:c;a>0?setTimeout(function(){return void ec(b)},a):ec(this)};
function ec(a){if(a.g.data.length>0){var b=a.B,c=a.i,f=a.A,d=a.g,g=[];var k=v(d.i);for(var e=k.next();!e.done;e=k.next())e=e.value,g.push(dc(e.key,e.value,void 0,!0));k=[];d=v(d.data);for(e=d.next();!e.done;e=d.next())e=e.value,k.push(dc(e.key,e.value,e.channel,!1));d=new ac;g=qb(d,1,g);k=qb(g,2,k);g=new $b;k=ob(k,1).concat(ob(k,2));g=qb(g,1,k);b&&jb(g,2,L(b));f&&jb(g,4,L(f));c&&jb(g,5,c==null?c:Va(c));b=g.i();var h;h===void 0&&(h=0);if(!y)for(y={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),
f=["+/=","+/","-_=","-_.","-_"],g=0;g<5;g++)for(k=c.concat(f[g].split("")),wa[g]=k,d=0;d<k.length;d++)e=k[d],y[e]===void 0&&(y[e]=d);h=wa[h];c=Array(Math.floor(b.length/3));f=h[64]||"";for(g=k=0;k<b.length-2;k+=3){var l=b[k],m=b[k+1];e=b[k+2];d=h[l>>2];l=h[(l&3)<<4|m>>4];m=h[(m&15)<<2|e>>6];e=h[e&63];c[g++]=d+l+m+e}d=0;e=f;switch(b.length-k){case 2:d=b[k+1],e=h[(d&15)<<2]||f;case 1:b=b[k],c[g]=h[b>>2]+h[(b&3)<<4|d>>4]+e+f}h="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+c.join("").replace(/\//g,
"_").replace(/\+/g,"-");b=window;var n=n===void 0?!1:n;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&typeof b.navigator.sendBeacon==="function"?b.navigator.sendBeacon(h):ua(b,h,n===void 0?!1:n);a.g.data=[]}}if(!window.mys||!window.mys.pingback)for(var fc=new X,gc=["mys","pingback"],Y=x,Z;gc.length&&(Z=gc.shift());)gc.length||fc===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=fc;}).call(this);
